cluster_name: ethereum-validators
monitoring:
  auto_discovery: true
  discovery_frequency: weekly
  enabled: true
  performance_enabled: true
networks:
- mainnet
nodes:
- ethereum_clients_enabled: true
  name: rocketpool
  ssh_user: root
  stack:
  - rocketpool
  - eth-docker
  tailscale_domain: minitx.velociraptor-scylla.ts.net
- ethereum_clients_enabled: true
  name: etherfi
  ssh_user: root
  stack:
  - obol
  - eth-docker
  tailscale_domain: orangepi5-plus.velociraptor-scylla.ts.net
- ethereum_clients_enabled: true
  name: lido102
  ssh_user: root
  stack:
  - obol
  - eth-docker
  tailscale_domain: minipcamd.velociraptor-scylla.ts.net
- ethereum_clients_enabled: true
  name: lido188
  ssh_user: root
  stack:
  - obol
  - eth-docker
  tailscale_domain: minipcamd2.velociraptor-scylla.ts.net
- ethereum_clients_enabled: true
  name: nodeset
  ssh_user: root
  stack:
  - hyperdrive
  - stakewise
  - obol
  - eth-docker
  tailscale_domain: minipcamd3.velociraptor-scylla.ts.net
- ethereum_clients_enabled: true
  name: stakewiseobol
  ssh_user: root
  stack:
  - obol
  - eth-docker
  tailscale_domain: opi5.velociraptor-scylla.ts.net
- ethereum_clients_enabled: true
  is_local: true
  name: eliedesk
  stack:
  - eth-docker
  tailscale_domain: localhost
