# Ethereum Validators Configuration

nodes:
  # Example node configuration
  - name: "minipcamd"
    ssh_user: "egk"
    eth_docker_path: "/home/egk/eth-docker"
    exec_client: "nethermind"
    consensus_client: "nimbus"
    beacon_api_port: 5051
    stack: "eth-docker"
    tailscale_domain: "minipcamd.velociraptor-scylla.ts.net"
  
  - name: "minipcamd2"
    ssh_user: "egk"
    eth_docker_path: "/home/egk/eth-docker"
    exec_client: "reth"
    consensus_client: "lighthouse"
    beacon_api_port: 5052
    stack: "eth-docker"
    tailscale_domain: "minipcamd2.velociraptor-scylla.ts.net"
  - name: "minipcamd3"
    ssh_user: "egk"
    eth_docker_path: "/home/egk/eth-docker"
    exec_client: "besu"
    consensus_client: "teku"
    beacon_api_port: 5052
    tailscale_domain: "minipcamd3.velociraptor-scylla.ts.net"
  - name: "laptop"
    ssh_user: "egk"
    eth_docker_path: "/home/egk/eth-docker"
    exec_client: "nethermind"
    consensus_client: "grandine"
    beacon_api_port: 5052
    tailscale_domain: "laptop.velociraptor-scylla.ts.net"
  - name: "minitx"
    ssh_user: "egk"
    eth_docker_path: "/home/egk/eth-docker"
    exec_client: "nethermind"
    consensus_client: "lighthouse"
    beacon_api_port: 5052
    tailscale_domain: "minitx.velociraptor-scylla.ts.net"
  - name: "orangepi5-plus"
    ssh_user: "egk"
    eth_docker_path: "/home/egk/eth-docker"
    exec_client: "geth"
    consensus_client: "nimbus"
    beacon_api_port: 5051
    stack: "eth-docker"
    tailscale_domain: "orangepi5-plus.velociraptor-scylla.ts.net"
  - name: "opi5"
    ssh_user: "egk"
    eth_docker_path: "/home/egk/eth-docker"
    exec_client: ""
    consensus_client: ""
    beacon_api_port: 5052
    stack: "eth-docker"
    tailscale_domain: "opi5.velociraptor-scylla.ts.net"
  # Add more nodes below